services:
  db:
    image: postgres:17
    container_name: gamestore-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gamestore_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gamestore_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./Server
      dockerfile: DockerFile
    container_name: gamestore-server
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=gamestore_db;Username=user;Password=password
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5210:8080"

  client:
    build:
      context: ./Client
      dockerfile: DockerFile
    container_name: gamestore-client
    depends_on:
      - server
    ports:
      - "80:80"

volumes:
  pgdata: